var Foto=function()
{
	this.idFoto;
	this.urlFoto;
	this.ancho,
	this.alto;
	this.proporcion;
	this.idFbFoto;
	this.ranking;
	this.idPerfil;
	this.nombrePerfil;
};
Foto.prototype={
	getFotos:function(id,callback)
	{
		var fotos=[];
		$.ajax({
			type:'GET',
			url:'../API/controlador/verFotosPerfil.php?idPerfil='+id,
			//data:{get_param,:value},
			dataType:'json',
			success:function(data){
				for(var i=0;i<data.length;i++)
				{
					var foto=new Foto();
					foto.idFoto=data[i].idFoto;
					foto.urlFoto=data[i].urlFoto;
					foto.ancho=data[i].ancho;
					foto.alto=data[i].alto;
					foto.proporcion=data[i].proporcion;
					foto.idFbFoto=data[i].idFbFoto;
					foto.ranking=data[i].ranking;
					foto.idPerfil=data[i].idPerfil;
					foto.nombrePerfil=data[i].nombrePerfil;
					
					fotos.push(foto);
				}
				//$fotos.append(html);
				callback(fotos,true);
			},
			error:function(error)
			{
				callback(undefined,false);
			}
		});
	},
	borrarFoto:function(id,callback)
	{
		$.ajax({
			type:'GET',
			url:'../API/controlador/eliminarFoto.php?idFoto='+id,
			//data:{get_param,:value},
			dataType:'json',
			success:function(data){
				if(data[0].res=="200"){
					callback(true);
				}else
				{
					callback(false);
				}
			},
			error:function(error)
			{
				callback(false);
			}
		});	
	}
}
